<?php
/**
 * @file
 * Code for the HumanitarianResponse Media feature.
 */

include_once('humanitarianresponse_media.features.inc');

//Add more view modes for Media formatting.
function humanitarianresponse_media_entity_info_alter(&$entity_info) {

  //Not sure if it's still an issue, but a previous commenter noted that Media module only recognizes view modes with the prefix media_. Also, as you can see by the entity type 'file', this is for after the switch-to-file-entity patch.
  $entity_info['file']['view modes']['media_home_slideshow'] = array(
    'label' => t('Home slideshow'),
    'custom settings' => TRUE,
  );

}
